version: "3.9"

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-local}/${COMPOSE_PROJECT_NAME:-kotobamichi-backend}:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
